# Generated by Django 6.0.6 on 2026-07-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism va Familiya')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('telegram_username', models.CharField(max_length=100, verbose_name='Telegram Username')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bogʻlanildi'), ('APPROVED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField(default=1, verbose_name='Son raqami')),
                ('title', models.CharField(max_length=255, verbose_name='Jurnal sarlavhasi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('front_cover', models.ImageField(upload_to='journals/covers/', verbose_name='Old muqova rasmi')),
                ('back_cover', models.ImageField(blank=True, null=True, upload_to='journals/covers/', verbose_name='Orqa muqova rasmi')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='journals/pdfs/', verbose_name='PDF fayl (Yuklab olish uchun)')),
                ('pages_count', models.PositiveIntegerField(default=48, verbose_name='Betlar soni')),
                ('issn', models.CharField(default='ISSN 2023-1234', max_length=50, verbose_name='ISSN raqami')),
                ('release_date', models.CharField(default='Iyun 2024', max_length=100, verbose_name='Chop etilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol / Nashr etilgan')),
            ],
            options={
                'verbose_name': 'Online Jurnal',
                'verbose_name_plural': 'Online Jurnallar',
                'ordering': ['-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism va Familiya')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL slagi')),
                ('sphere', models.CharField(choices=[('biznes', 'Tadbirkorlik & Biznes'), ('texno', 'Texnologiya & IT'), ('sport', 'Sport'), ('fan', 'Fan & Taʻlim'), ('sanat', 'Sanʻat & Madaniyat'), ('tibbiyot', 'Tibbiyot'), ('ijtimoiy', 'Ijtimoiy faoliyat')], max_length=50, verbose_name='Soha')),
                ('region', models.CharField(choices=[('Toshkent', 'Toshkent shahri'), ('Samarqand', 'Samarqand'), ('Fargʻona', 'Fargʻona'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Navoiy', 'Navoiy'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Toshkent viloyati', 'Toshkent viloyati')], max_length=100, verbose_name='Viloyat')),
                ('photo', models.ImageField(upload_to='leaders/', verbose_name='Portret rasm')),
                ('short_bio', models.CharField(max_length=255, verbose_name='Qisqa tavsif / Unvon')),
                ('full_bio', models.TextField(blank=True, verbose_name='Toʻliq biografiya va yutuqlar')),
                ('birth_date', models.CharField(blank=True, max_length=100, verbose_name='Tugʻilgan sana')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Tugʻilgan joy')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='Taʻlim')),
                ('top100_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='TOP 100 reyting oʻrni')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifada koʻrsatish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qoʻshilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yetakchi',
                'verbose_name_plural': 'Yetakchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(verbose_name='Iqtibos matni')),
                ('author_name', models.CharField(max_length=255, verbose_name='Muallif ismi')),
                ('author_title', models.CharField(max_length=255, verbose_name='Muallif kasbi / unvoni')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Bosh sahifada koʻrsatish')),
            ],
            options={
                'verbose_name': 'Iqtibos',
                'verbose_name_plural': 'Iqtiboslar',
            },
        ),
    ]
