# Generated by Django 6.0.6 on 2026-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.CharField(default='OʻzYYE Bosh Tahririyati', max_length=255, verbose_name='Muallif / Tahririyat'),
        ),
        migrations.AddField(
            model_name='journal',
            name='file_size',
            field=models.CharField(default='24 MB', max_length=50, verbose_name='Fayl hajmi'),
        ),
    ]
