# Generated by Django 6.0.6 on 2026-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journal_author_journal_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='quote_poster',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/quotes/', verbose_name='Iqtibos poster rasmi (Rasm sifatida)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='OʻzYE Bosh Tahririyati', max_length=255, verbose_name='Muallif / Tahririyat'),
        ),
    ]
