# Generated by Django 6.0.6 on 2026-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leader_quote_poster_alter_journal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yashash joyi'),
        ),
        migrations.AddField(
            model_name='leader',
            name='quote',
            field=models.CharField(blank=True, max_length=400, verbose_name='Shaxsiy iqtibos (poster uchun)'),
        ),
        migrations.AddField(
            model_name='leader',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO kalit soʻzlar'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='OʻzYYE Bosh Tahririyati', max_length=255, verbose_name='Muallif / Tahririyat'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pages_count',
            field=models.PositiveIntegerField(default=48, verbose_name='Sahifalar soni'),
        ),
    ]
