# Generated by Django 6.0.6 on 2026-07-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leader_current_location_leader_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='seo_keywords',
        ),
        migrations.AddField(
            model_name='quote',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/authors/', verbose_name='Muallif rasmi'),
        ),
        migrations.AddField(
            model_name='quote',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.leader', verbose_name='Tegishli Yetakchi'),
        ),
        migrations.AddField(
            model_name='quote',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/posters/', verbose_name='Tayyor iqtibos poster rasmi'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='OʻzYYE Nashri', max_length=255, verbose_name='Muallif / Nashr'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pages_count',
            field=models.PositiveIntegerField(default=48, verbose_name='Betlar soni'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='top100_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TOP 100 oʻrni'),
        ),
    ]
