# Generated by Django 6.0.6 on 2026-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_leader_current_location_remove_leader_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='poster_image',
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='OʻzYYE Bosh Tahririyati', max_length=255, verbose_name='Muallif / Tahririyat'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol / Eʼlon qilingan'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pages_count',
            field=models.PositiveIntegerField(default=48, verbose_name='Sahifalar soni'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/', verbose_name='Muallif rasmi'),
        ),
    ]
