# Generated by Django 6.0.6 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_quote_leader_remove_quote_poster_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name="Jurnal boʻlimini 'Tez orada' (Coming Soon) holatiga oʻtkazish")),
                ('coming_soon_title', models.CharField(default='Online Jurnal — Tez orada!', max_length=255, verbose_name="'Tez orada' sarlavhasi")),
                ('coming_soon_description', models.TextField(default='Oʻzbekiston Yetakchi Yoshlari online jurnalining yangi soni va barcha nashrlari tayyorlanmoqda. Tez orada ushbu boʻlimda taqdim etiladi!', verbose_name="'Tez orada' tavsifi")),
            ],
            options={
                'verbose_name': 'Jurnal Sozlamasi',
                'verbose_name_plural': 'Jurnal Sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/posters/', verbose_name='Iqtibos poster rasmi (Rasm)'),
        ),
    ]
