# Generated by Django 6.0.6 on 2026-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_journalsetting_quote_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='Oʻzbekiston Yetakchi Yoshlari', max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/posters/', verbose_name='Iqtibos poster rasmi'),
        ),
    ]
