# Generated by Django 6.0.6 on 2026-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_journal_author_alter_quote_poster_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalSetting',
        ),
        migrations.AlterField(
            model_name='quote',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/posters/', verbose_name='Iqtibos poster rasmi (Rasm sifatida)'),
        ),
    ]
