# Generated by Django 6.0.6 on 2026-07-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_quote_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya (masalan: LIDERLIK & INTIZOM)')),
                ('title', models.CharField(max_length=255, verbose_name='Maqola sarlavhasi')),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif (Ushbu sonda nimalar bor uchun)')),
                ('author_name', models.CharField(max_length=255, verbose_name='Muallif ismi')),
                ('page_number', models.PositiveIntegerField(verbose_name='Sahifa raqami (Jurnal ichida)')),
                ('content', models.TextField(verbose_name='Maqola matni (paragraflar uchun)')),
                ('pull_quote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Iqtibos (Pull quote)')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.journal', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Jurnal Maqolasi',
                'verbose_name_plural': 'Jurnal Maqolalari',
                'ordering': ['page_number'],
            },
        ),
    ]
