# Generated by Django 6.0.6 on 2026-07-23 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_journalarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='full_bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Toʻliq biografiya va yutuqlar'),
        ),
    ]
