# Generated by Django 6.0.6 on 2026-07-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_leader_full_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='top100_rank',
        ),
    ]
