# Generated by Django 6.0.6 on 2026-07-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_quote_remove_leader_top100_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='quote_poster_1x1',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/quotes/1x1/', verbose_name='Iqtibos poster rasmi (1:1 kvadrat)'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='quote_poster',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/quotes/', verbose_name='Iqtibos poster rasmi (16:9 keng)'),
        ),
    ]
