# Generated by Django 6.0.6 on 2026-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_leader_quote_poster_1x1_alter_leader_quote_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=255, verbose_name='F.I.SH. (Familiya, ism, sharif)'),
        ),
    ]
