# Generated by Django 6.0.6 on 2026-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_leader_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif / Unvon'),
        ),
    ]
