# Generated by Django 6.0.6 on 2026-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_leader_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='bio_file',
            field=models.FileField(blank=True, null=True, upload_to='bios/', verbose_name='Biografiya fayli (PDF/DOCX, ixtiyoriy)'),
        ),
    ]
