# Generated by Django 6.0.6 on 2026-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_leader_bio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa status (masalan: Ijodkor | Jamoatchilik faoli)'),
        ),
    ]
