# Generated by Django 6.0.6 on 2026-07-30 16:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_leader_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bog‘lanildi'), ('APPROVED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(default='O‘zbekiston Yetakchi Yoshlari', max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tug‘ilgan joy'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='full_bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='To‘liq biografiya va yutuqlar'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Bosh sahifada ko‘rsatish'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent shahri'), ('Samarqand', 'Samarqand'), ('Farg‘ona', 'Farg‘ona'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Navoiy', 'Navoiy'), ('Qoraqalpog‘iston', 'Qoraqalpog‘iston'), ('Toshkent viloyati', 'Toshkent viloyati')], max_length=100, verbose_name='Hudud'),
        ),
    ]
