# Generated by Django 5.2.16 on 2026-07-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_leader_show_quote_alter_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='is_quote_featured',
            field=models.BooleanField(default=False, verbose_name="Bosh sahifada iqtibosini ko'rsatish"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='show_quote',
            field=models.BooleanField(default=False, verbose_name="Iqtiboslar sahifasida ko'rsatish (Top)"),
        ),
    ]
