# Generated by Django 5.2.16 on 2026-07-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_leader_is_quote_featured_alter_leader_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='show_in_leaders',
            field=models.BooleanField(default=False, verbose_name="Yetakchilar sahifasida ko'rsatish (Top)"),
        ),
        migrations.AlterField(
            model_name='leader',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Bosh sahifada yetakchini ko'rsatish"),
        ),
    ]
