# Generated by Django 5.2.16 on 2026-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_leader_show_in_leaders_alter_leader_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bog‘lanildi'), ('UNREACHABLE', 'Bog‘lanib bo‘lmadi'), ('APPROVED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holat'),
        ),
    ]
