# Generated by Django 5.2.16 on 2026-08-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='sphere',
            field=models.CharField(choices=[('biznes', 'Tadbirkorlik & Biznes'), ('texno', 'Texnologiya & IT'), ('sport', 'Sport'), ('fan', 'Fan & Taʼlim'), ('sanat', 'Sanʼat & Madaniyat'), ('tibbiyot', 'Tibbiyot'), ('ijtimoiy', 'Ijtimoiy faoliyat'), ('media', 'Media va Jurnalistika')], max_length=50, verbose_name='Soha'),
        ),
    ]
