# Generated by Django 5.2.16 on 2026-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_leader_sphere'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name="To'langan summa (so'mda)"),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full', 'Bir martada — 80,000 so‘m'), ('installment', 'Bo‘lib-bo‘lib — 12 kun')], max_length=20, null=True, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='application',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Bot xabar IDsi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bog‘lanildi'), ('UNREACHABLE', 'Bog‘lanib bo‘lmadi'), ('APPROVED', 'Qabul qilindi — To‘lov kutilmoqda'), ('REJECTED', 'Rad etildi'), ('IN_PROGRESS', 'Jarayonda (To‘lov boshlandi)'), ('COMPLETED', 'Yakunlandi (To‘liq to‘landi)')], default='NEW', max_length=20, verbose_name='Holat'),
        ),
    ]
