# Generated by Django 5.2.16 on 2026-08-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_application_paid_amount_application_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='To‘langan summa (so‘mda)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full', 'Bir martada — 80,000 so‘m'), ('installment', 'Bo‘lib-bo‘lib — 12 kun')], max_length=20, null=True, verbose_name='To‘lov turi'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategoriya (masalan: LIDERLIK va INTIZOM)'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='sphere',
            field=models.CharField(choices=[('biznes', 'Tadbirkorlik va Biznes'), ('texno', 'Texnologiya va IT'), ('sport', 'Sport'), ('fan', 'Fan va Taʼlim'), ('sanat', 'Sanʼat va Madaniyat'), ('tibbiyot', 'Tibbiyot'), ('ijtimoiy', 'Ijtimoiy faoliyat'), ('media', 'Media va Jurnalistika')], max_length=50, verbose_name='Soha'),
        ),
    ]
