# Generated by Django 5.2.16 on 2026-08-04 15:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_application_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha (masalan: Edu Grands...)')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Davlat (masalan: Turkiya 🇹🇷)')),
                ('format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dastur shakli (masalan: Oflayn)')),
                ('age_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yosh toifasi (masalan: 18-30)')),
                ('description', ckeditor.fields.RichTextField(verbose_name="Batafsil ma’lumot (Matn va imtiyozlar)")),
                ('registration_link', models.URLField(blank=True, max_length=500, null=True, verbose_name="Ro‘yxatdan o‘tish havolasi")),
                ('deadline', models.CharField(blank=True, max_length=100, null=True, verbose_name="So‘nggi muddat (masalan: 30-Avgust)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/', verbose_name='Rasm / Poster')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol / E'lon qilingan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo‘shilgan sana")),
            ],
            options={
                'verbose_name': 'Imkoniyat (Grant/Dastur)',
                'verbose_name_plural': 'Imkoniyatlar (Grantlar/Dasturlar)',
                'ordering': ['-created_at'],
            },
        ),
    ]
