# Generated by Django 5.2.16 on 2026-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_opportunity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maxsus belgi (Masalan: Maxsus grant)'),
        ),
    ]
