# Generated by Django 5.2.16 on 2026-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_opportunity_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Haqiqiy sana (Avtomatlashtirish uchun)'),
        ),
    ]
