# Generated by Django 5.2.16 on 2026-08-04 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_opportunity_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='UUID (URL uchun)'),
        ),
    ]
