# Generated by Django 5.2.16 on 2026-08-04 21:39

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    Opportunity = apps.get_model('core', 'Opportunity')
    for row in Opportunity.objects.all():
        if not row.slug:
            row.slug = str(uuid.uuid4())
            row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_opportunity_uuid_alter_application_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]

