# Generated by Django 5.2.16 on 2026-08-04 21:48

import uuid
from django.db import migrations

def force_gen_uuid(apps, schema_editor):
    Opportunity = apps.get_model('core', 'Opportunity')
    for row in Opportunity.objects.all():
        if not row.slug or len(str(row.slug).strip()) < 5:
            row.slug = str(uuid.uuid4())
            row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_populate_opportunity_slugs'),
    ]

    operations = [
        migrations.RunPython(force_gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
