# Generated by Django 5.2.16 on 2026-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_fix_slugs_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol / E’lon qilingan'),
        ),
    ]
