# Generated by Django 5.2.16 on 2026-08-06 23:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_opportunity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='photo',
            field=models.ImageField(upload_to=core.models.get_profile_image_path, verbose_name='Portret rasm'),
        ),
    ]
