COUNTRY_CHOICES = (
    ("Afg‘oniston", "Afg‘oniston"),
    ("Albaniya", "Albaniya"),
    ("Jazoir", "Jazoir"),
    ("Andorra", "Andorra"),
    ("Angola", "Angola"),
    ("Antigua va Barbuda", "Antigua va Barbuda"),
    ("Argentina", "Argentina"),
    ("Armaniston", "Armaniston"),
    ("Avstraliya", "Avstraliya"),
    ("Avstriya", "Avstriya"),
    ("Ozarbayjon", "Ozarbayjon"),
    ("Bagama orollari", "Bagama orollari"),
    ("Bahrayn", "Bahrayn"),
    ("Bangladesh", "Bangladesh"),
    ("Barbados", "Barbados"),
    ("Belarus", "Belarus"),
    ("Belgiya", "Belgiya"),
    ("Beliz", "Beliz"),
    ("Benin", "Benin"),
    ("Butan", "Butan"),
    ("Boliviya", "Boliviya"),
    ("Bosniya va Gersegovina", "Bosniya va Gersegovina"),
    ("Botsvana", "Botsvana"),
    ("Braziliya", "Braziliya"),
    ("Bruney", "Bruney"),
    ("Bolgariya", "Bolgariya"),
    ("Burkina-Faso", "Burkina-Faso"),
    ("Burundi", "Burundi"),
    ("Kabo-Verde", "Kabo-Verde"),
    ("Kambodja", "Kambodja"),
    ("Kamerun", "Kamerun"),
    ("Kanada", "Kanada"),
    ("Markaziy Afrika Respublikasi", "Markaziy Afrika Respublikasi"),
    ("Chad", "Chad"),
    ("Chili", "Chili"),
    ("Xitoy", "Xitoy"),
    ("Kolumbiya", "Kolumbiya"),
    ("Komor orollari", "Komor orollari"),
    ("Kongo Demokratik Respublikasi", "Kongo Demokratik Respublikasi"),
    ("Kongo Respublikasi", "Kongo Respublikasi"),
    ("Kosta-Rika", "Kosta-Rika"),
    ("Xorvatiya", "Xorvatiya"),
    ("Kuba", "Kuba"),
    ("Kipr", "Kipr"),
    ("Chexiya", "Chexiya"),
    ("Daniya", "Daniya"),
    ("Jibuti", "Jibuti"),
    ("Dominika", "Dominika"),
    ("Dominikan Respublikasi", "Dominikan Respublikasi"),
    ("Sharqiy Timor", "Sharqiy Timor"),
    ("Ekvador", "Ekvador"),
    ("Misr", "Misr"),
    ("Salvador", "Salvador"),
    ("Ekvatorial Gvineya", "Ekvatorial Gvineya"),
    ("Eritreya", "Eritreya"),
    ("Estoniya", "Estoniya"),
    ("Esvatini", "Esvatini"),
    ("Efiopiya", "Efiopiya"),
    ("Fiji", "Fiji"),
    ("Finlyandiya", "Finlyandiya"),
    ("Fransiya", "Fransiya"),
    ("Gabon", "Gabon"),
    ("Gambiya", "Gambiya"),
    ("Gruziya", "Gruziya"),
    ("Germaniya", "Germaniya"),
    ("Gana", "Gana"),
    ("Gretsiya", "Gretsiya"),
    ("Grenada", "Grenada"),
    ("Gvatemala", "Gvatemala"),
    ("Gvineya", "Gvineya"),
    ("Gvineya-Bisau", "Gvineya-Bisau"),
    ("Gayana", "Gayana"),
    ("Gaiti", "Gaiti"),
    ("Gonduras", "Gonduras"),
    ("Vengriya", "Vengriya"),
    ("Islandiya", "Islandiya"),
    ("Hindiston", "Hindiston"),
    ("Indoneziya", "Indoneziya"),
    ("Eron", "Eron"),
    ("Iroq", "Iroq"),
    ("Irlandiya", "Irlandiya"),
    ("Isroil", "Isroil"),
    ("Italiya", "Italiya"),
    ("Kot-d'Ivuar", "Kot-d'Ivuar"),
    ("Yamayka", "Yamayka"),
    ("Yaponiya", "Yaponiya"),
    ("Iordaniya", "Iordaniya"),
    ("Qozog‘iston", "Qozog‘iston"),
    ("Keniya", "Keniya"),
    ("Kiribati", "Kiribati"),
    ("Kuvayt", "Kuvayt"),
    ("Qirg‘iziston", "Qirg‘iziston"),
    ("Laos", "Laos"),
    ("Latviya", "Latviya"),
    ("Livan", "Livan"),
    ("Lesoto", "Lesoto"),
    ("Liberiya", "Liberiya"),
    ("Liviya", "Liviya"),
    ("Lixtenshteyn", "Lixtenshteyn"),
    ("Litva", "Litva"),
    ("Lyuksemburg", "Lyuksemburg"),
    ("Madagaskar", "Madagaskar"),
    ("Malavi", "Malavi"),
    ("Malayziya", "Malayziya"),
    ("Maldiv orollari", "Maldiv orollari"),
    ("Mali", "Mali"),
    ("Malta", "Malta"),
    ("Marshall orollari", "Marshall orollari"),
    ("Mavritaniya", "Mavritaniya"),
    ("Mavrikiy", "Mavrikiy"),
    ("Meksika", "Meksika"),
    ("Mikroneziya", "Mikroneziya"),
    ("Moldova", "Moldova"),
    ("Monako", "Monako"),
    ("Mo‘g‘uliston", "Mo‘g‘uliston"),
    ("Chernogoriya", "Chernogoriya"),
    ("Marokash", "Marokash"),
    ("Mozambik", "Mozambik"),
    ("Myanma", "Myanma"),
    ("Namibiya", "Namibiya"),
    ("Nauru", "Nauru"),
    ("Nepal", "Nepal"),
    ("Niderlandiya", "Niderlandiya"),
    ("Yangi Zelandiya", "Yangi Zelandiya"),
    ("Nikaragua", "Nikaragua"),
    ("Niger", "Niger"),
    ("Nigeriya", "Nigeriya"),
    ("Shimoliy Koreya", "Shimoliy Koreya"),
    ("Shimoliy Makedoniya", "Shimoliy Makedoniya"),
    ("Norvegiya", "Norvegiya"),
    ("Ummon", "Ummon"),
    ("Pokiston", "Pokiston"),
    ("Palau", "Palau"),
    ("Falastin", "Falastin"),
    ("Panama", "Panama"),
    ("Papua-Yangi Gvineya", "Papua-Yangi Gvineya"),
    ("Paragvay", "Paragvay"),
    ("Peru", "Peru"),
    ("Filippin", "Filippin"),
    ("Polsha", "Polsha"),
    ("Portugaliya", "Portugaliya"),
    ("Qatar", "Qatar"),
    ("Ruminiya", "Ruminiya"),
    ("Rossiya", "Rossiya"),
    ("Ruanda", "Ruanda"),
    ("Sent-Kits va Nevis", "Sent-Kits va Nevis"),
    ("Sent-Lyusiya", "Sent-Lyusiya"),
    ("Sent-Vinsent va Grenadinlar", "Sent-Vinsent va Grenadinlar"),
    ("Samoa", "Samoa"),
    ("San-Marino", "San-Marino"),
    ("San-Tome va Prinsipi", "San-Tome va Prinsipi"),
    ("Saudiya Arabistoni", "Saudiya Arabistoni"),
    ("Senegal", "Senegal"),
    ("Serbiya", "Serbiya"),
    ("Seyshel orollari", "Seyshel orollari"),
    ("Syerra-Leone", "Syerra-Leone"),
    ("Singapur", "Singapur"),
    ("Slovakiya", "Slovakiya"),
    ("Sloveniya", "Sloveniya"),
    ("Solomon orollari", "Solomon orollari"),
    ("Somali", "Somali"),
    ("Janubiy Afrika", "Janubiy Afrika"),
    ("Janubiy Koreya", "Janubiy Koreya"),
    ("Janubiy Sudan", "Janubiy Sudan"),
    ("Ispaniya", "Ispaniya"),
    ("Shri-Lanka", "Shri-Lanka"),
    ("Sudan", "Sudan"),
    ("Surinam", "Surinam"),
    ("Shvetsiya", "Shvetsiya"),
    ("Shveytsariya", "Shveytsariya"),
    ("Suriya", "Suriya"),
    ("Tojikiston", "Tojikiston"),
    ("Tanzaniya", "Tanzaniya"),
    ("Tailand", "Tailand"),
    ("Togo", "Togo"),
    ("Tonga", "Tonga"),
    ("Trinidad va Tobago", "Trinidad va Tobago"),
    ("Tunis", "Tunis"),
    ("Turkiya", "Turkiya"),
    ("Turkmaniston", "Turkmaniston"),
    ("Tuvalu", "Tuvalu"),
    ("Uganda", "Uganda"),
    ("Ukraina", "Ukraina"),
    ("Birlashgan Arab Amirliklari", "Birlashgan Arab Amirliklari"),
    ("Buyuk Britaniya", "Buyuk Britaniya"),
    ("AQSh", "AQSh"),
    ("Urugvay", "Urugvay"),
    ("O‘zbekiston", "O‘zbekiston"),
    ("Vanuatu", "Vanuatu"),
    ("Vatikan", "Vatikan"),
    ("Venesuela", "Venesuela"),
    ("Vyetnam", "Vyetnam"),
    ("Yaman", "Yaman"),
    ("Zambiya", "Zambiya"),
    ("Zimbabve", "Zimbabve"),
    ("Global (Onlayn)", "Global (Onlayn)"),
)
